spring:
  application:
    name: auth-server
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      schema: app
      auto-commit: true
    url: jdbc:postgresql://localhost:5432/auth-server
  jpa:
    show-sql: true
server:
  port: 8080

