server:
  port: 8081


spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: login-service
            client-secret: lRvp7DOygVLOfSErbvBMx38YRxEZX4zf
            client-name: Users-application
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - secret.write
              - secret.know
              - secret.tell
        provider:
          keycloak:
            issuer-uri: "http://localhost:8282/realms/market"





